services:
  # AutoFlow Next.js Frontend Web Service
  - type: web
    name: autoflow-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NEXT_PUBLIC_NHOST_SUBDOMAIN
        value: wjxmytdjpgmndmnqjghy
      - key: NEXT_PUBLIC_NHOST_REGION
        value: ap-south-1

